Return-Path: <linux-samsung-soc-owner@vger.kernel.org>
X-Original-To: lists+linux-samsung-soc@lfdr.de
Delivered-To: lists+linux-samsung-soc@lfdr.de
Received: from vger.kernel.org (vger.kernel.org [23.128.96.18])
	by mail.lfdr.de (Postfix) with ESMTP id A3A01260EE2
	for <lists+linux-samsung-soc@lfdr.de>; Tue,  8 Sep 2020 11:40:02 +0200 (CEST)
Received: (majordomo@vger.kernel.org) by vger.kernel.org via listexpand
        id S1729171AbgIHJkB (ORCPT <rfc822;lists+linux-samsung-soc@lfdr.de>);
        Tue, 8 Sep 2020 05:40:01 -0400
Received: from mail2-relais-roc.national.inria.fr ([192.134.164.83]:11848 "EHLO
        mail2-relais-roc.national.inria.fr" rhost-flags-OK-OK-OK-OK)
        by vger.kernel.org with ESMTP id S1728886AbgIHJj7 (ORCPT
        <rfc822;linux-samsung-soc@vger.kernel.org>);
        Tue, 8 Sep 2020 05:39:59 -0400
X-IronPort-AV: E=Sophos;i="5.76,359,1592863200"; 
   d="scan'208";a="466564047"
Received: from abo-173-121-68.mrs.modulonet.fr (HELO hadrien) ([85.68.121.173])
  by mail2-relais-roc.national.inria.fr with ESMTP/TLS/DHE-RSA-AES256-GCM-SHA384; 08 Sep 2020 11:39:57 +0200
Date:   Tue, 8 Sep 2020 11:39:51 +0200 (CEST)
From:   Julia Lawall <julia.lawall@inria.fr>
X-X-Sender: jll@hadrien
To:     Brian Kim <brian.kim@hardkernel.com>
cc:     kbuild-all@lists.01.org, Dongjin Kim <tobetter@gmail.com>,
        memeka <mihailescu2m@gmail.com>,
        Yang Deokgyu <secugyu@gmail.com>,
        Arnd Bergmann <arnd@arndb.de>,
        Greg Kroah-Hartman <gregkh@linuxfoundation.org>,
        Kukjin Kim <kgene@kernel.org>,
        Krzysztof Kozlowski <krzk@kernel.org>,
        linux-arm-kernel@lists.infradead.org,
        linux-samsung-soc@vger.kernel.org
Subject: [PATCH] ODROID-XU4: char: exynos: fix platform_no_drv_owner.cocci
 warnings
Message-ID: <alpine.DEB.2.22.394.2009081136090.2478@hadrien>
User-Agent: Alpine 2.22 (DEB 394 2020-01-19)
MIME-Version: 1.0
Content-Type: text/plain; charset=US-ASCII
Sender: linux-samsung-soc-owner@vger.kernel.org
Precedence: bulk
List-ID: <linux-samsung-soc.vger.kernel.org>
X-Mailing-List: linux-samsung-soc@vger.kernel.org

No need to set .owner here. The core will do it.

Generated by: scripts/coccinelle/api/platform_no_drv_owner.cocci

Fixes: be904257f8a9 ("ODROID-XU4: char: exynos: add /dev/gpiomem device for rootless user GPIO access")
CC: Brian Kim <brian.kim@hardkernel.com>
Signed-off-by: kernel test robot <lkp@intel.com>
Signed-off-by: Julia Lawall <julia.lawall@inria.fr>
---

I received some other warnings about this file, but with no details:

>> drivers/char/exynos-gpiomem.c:231:15-18: ERROR: inst is NULL but
dereferenced.
--
>> drivers/char/exynos-gpiomem.c:231:9-13: ERROR: reference preceded by
free on line 229


tree:   https://github.com/tobetter/linux odroid-5.9.y
head:   1118f1d60573bfbf1eb7ef079fa879a498ba4313
commit: be904257f8a9bd689b360fa98d3ffc85bdbeb560 [53/69] ODROID-XU4: char: exynos: add /dev/gpiomem device for rootless user GPIO access
:::::: branch date: 4 hours ago
:::::: commit date: 4 hours ago

 exynos-gpiomem.c |    1 -
 1 file changed, 1 deletion(-)

--- a/drivers/char/exynos-gpiomem.c
+++ b/drivers/char/exynos-gpiomem.c
@@ -255,7 +255,6 @@ MODULE_DEVICE_TABLE(of, exynos_gpiomem_o
 static struct platform_driver exynos_gpiomem_driver = {
 	.driver			= {
 		.name		= DRIVER_NAME,
-		.owner		= THIS_MODULE,
 		.of_match_table	= exynos_gpiomem_of_match,
 	},
 	.probe			= exynos_gpiomem_probe,
