Return-Path: <linux-samsung-soc-owner@vger.kernel.org>
X-Original-To: lists+linux-samsung-soc@lfdr.de
Delivered-To: lists+linux-samsung-soc@lfdr.de
Received: from vger.kernel.org (vger.kernel.org [23.128.96.18])
	by mail.lfdr.de (Postfix) with ESMTP id 554F027F60B
	for <lists+linux-samsung-soc@lfdr.de>; Thu,  1 Oct 2020 01:33:38 +0200 (CEST)
Received: (majordomo@vger.kernel.org) by vger.kernel.org via listexpand
        id S1730498AbgI3Xdh convert rfc822-to-8bit (ORCPT
        <rfc822;lists+linux-samsung-soc@lfdr.de>);
        Wed, 30 Sep 2020 19:33:37 -0400
Received: from relmlor1.renesas.com ([210.160.252.171]:33028 "EHLO
        relmlie5.idc.renesas.com" rhost-flags-OK-OK-OK-FAIL)
        by vger.kernel.org with ESMTP id S1730338AbgI3Xdh (ORCPT
        <rfc822;linux-samsung-soc@vger.kernel.org>);
        Wed, 30 Sep 2020 19:33:37 -0400
X-Greylist: delayed 303 seconds by postgrey-1.27 at vger.kernel.org; Wed, 30 Sep 2020 19:33:37 EDT
Date:   01 Oct 2020 08:28:33 +0900
X-IronPort-AV: E=Sophos;i="5.77,322,1596466800"; 
   d="scan'208";a="58602614"
Received: from unknown (HELO relmlir5.idc.renesas.com) ([10.200.68.151])
  by relmlie5.idc.renesas.com with ESMTP; 01 Oct 2020 08:28:33 +0900
Received: from mercury.renesas.com (unknown [10.166.252.133])
        by relmlir5.idc.renesas.com (Postfix) with ESMTP id ACF024002C28;
        Thu,  1 Oct 2020 08:28:33 +0900 (JST)
Message-ID: <87v9fualv7.wl-kuninori.morimoto.gx@renesas.com>
From:   Kuninori Morimoto <kuninori.morimoto.gx@renesas.com>
To:     Marek Szyprowski <m.szyprowski@samsung.com>
Cc:     Mark Brown <broonie@kernel.org>,
        Linux-ALSA <alsa-devel@alsa-project.org>,
        'Linux Samsung SOC' <linux-samsung-soc@vger.kernel.org>,
        Sylwester Nawrocki <s.nawrocki@samsung.com>,
        Krzysztof Kozlowski <krzk@kernel.org>
Subject: Re: [PATCH 5/7] ASoC: soc-pcm: add soc_pcm_clean() and call it from soc_pcm_open/close()
In-Reply-To: <1fa68abd-a86c-7a29-6c28-9ecde75ab4c6@samsung.com>
References: <87mu1abwp2.wl-kuninori.morimoto.gx@renesas.com>
        <87ft72bwn4.wl-kuninori.morimoto.gx@renesas.com>
        <CGME20200929130814eucas1p1c09e7e1fe2d808d9bd41718cadf33754@eucas1p1.samsung.com>
        <1fa68abd-a86c-7a29-6c28-9ecde75ab4c6@samsung.com>
User-Agent: Wanderlust/2.15.9 Emacs/26.3 Mule/6.0
MIME-Version: 1.0 (generated by SEMI-EPG 1.14.7 - "Harue")
Content-Type: text/plain; charset=ISO-8859-1
Content-Transfer-Encoding: 8BIT
Precedence: bulk
List-ID: <linux-samsung-soc.vger.kernel.org>
X-Mailing-List: linux-samsung-soc@vger.kernel.org


Hi Marek

Thank you for testing.
I will check it

> On 28.09.2020 02:01, Kuninori Morimoto wrote:
> > From: Kuninori Morimoto <kuninori.morimoto.gx@renesas.com>
> >
> > soc_pcm_open() does rollback when failed (A),
> > but, it is almost same as soc_pcm_close().
> >
> > 	static int soc_pcm_open(xxx)
> > 	{
> > 		...
> > 		if (ret < 0)
> > 			goto xxx_err;
> > 		...
> > 		return 0;
> >
> >   ^	config_err:
> >   |		...
> >   |	rtd_startup_err:
> > (A)		...
> >   |	component_err:
> >   |		...
> >   v		return ret;
> > 	}
> >
> > The difference is
> > soc_pcm_close() is for all dai/component/substream,
> > rollback        is for succeeded part only.
> >
> > This kind of duplicated code can be a hotbed of bugs,
> > thus, we want to share soc_pcm_close() and rollback.
> >
> > Now, soc_pcm_open/close() are handling
> > 	1) snd_soc_dai_startup/shutdown()
> > 	2) snd_soc_link_startup/shutdown()
> > 	3) snd_soc_component_module_get/put()
> > 	4) snd_soc_component_open/close()
> > 	5) pm_runtime_put/get()
> >
> > Now, 1) to 5) are handled.
> > This patch adds new soc_pcm_clean() and call it from
> > soc_pcm_open() as rollback, and from soc_pcm_close() as
> > normal close handler.
> >
> > One note here is that it don't need to call snd_soc_runtime_deactivate()
> > when rollback case, because it will be called without
> > snd_soc_runtime_activate().
> > It also don't need to call snd_soc_dapm_stream_stop() when rollback case.
> >
> > Signed-off-by: Kuninori Morimoto <kuninori.morimoto.gx@renesas.com>
> 
> This patch landed in linux next-20200929 as commit 140a4532cdb8 ("ASoC: 
> soc-pcm: add soc_pcm_clean() and call it from soc_pcm_open/close()"). 
> Sadly it causes a regression in ALSA operation on my various test 
> boards: Exynos4412 based Trats2, Exynos5410 based Odroid XU, Exynos5250 
> Snow Chromebook and other. The first app, which tries to open ALSA 
> device fails. Then, on the second try, it work.
> 
> Here is a log from Odroid XU:
> 
> [    3.775032] max98090 1-0010: MAX98090 REVID=0x43
> [    3.781958] max98090 1-0010: use default 2.8v micbias
> [    3.812813] ALSA device list:
> [    3.814448]   #0: Odroid-XU
> 
> # speaker-test -l1
> 
> speaker-test 1.1.3
> 
> Playback device is default
> Stream parameters are 48000Hz, S16_LE, 1 channels
> Using 16 octaves of pink noise
> Playback open error: -22,Invalid argument
> # speaker-test -l1
> 
> speaker-test 1.1.3
> 
> Playback device is default
> Stream parameters are 48000Hz, S16_LE, 1 channels
> Using 16 octaves of pink noise
> Rate set to 48000Hz (requested 48000Hz)
> Buffer size range from 128 to 131072
> Period size range from 64 to 65536
> Using max buffer size 131072
> Periods = 4
> was set period_size = 32768
> was set buffer_size = 131072
>   0 - Front Left
> Time per period = 0.029512
> #
> 
>  > ...
> 
> Best regards
> -- 
> Marek Szyprowski, PhD
> Samsung R&D Institute Poland
> 
